#!/usr/bin/python

import sys
import os
import os.path as path

from common.service import Launcher
from common import configobj
from common.mylogger import *

binary = "cmWorker.Manager"
curdir = path.dirname(path.abspath(__file__))
sys.path.append(curdir)

if __name__ == "__main__":
	args = sys.argv
	servicename = path.basename(args[0])
	launcher = Launcher(servicename, binary)
	if len(args) == 2:
		action = args[1].strip()
		if action == "start":
			launcher.start()
		elif action == "stop":
			launcher.stop()
		elif action == "restart":
			launcher.restart()
		else:
			launcher.help()
	else:
		launcher.help()

